name: MyTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Python unit tests
      run: python -u -m unittest Tests/test.py

    - name: Coveralls
    - uses: coverallsapp/github-action@v2

