name: MyTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls

    - name: Run Python unit tests
      run: |
        coverage run -m unittest discover -s Tests/test.py
        coverage report
        coverage xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2

